const CAPITALS={
Africa:[
{flag:"🇳🇬",name:"Nigeria",capital:"Abuja"},
{flag:"🇪🇬",name:"Egypt",capital:"Cairo"},
{flag:"🇿🇦",name:"South Africa",capital:"Pretoria"},
{flag:"🇰🇪",name:"Kenya",capital:"Nairobi"},
{flag:"🇪🇹",name:"Ethiopia",capital:"Addis Ababa"},
{flag:"🇲🇦",name:"Morocco",capital:"Rabat"},
{flag:"🇬🇭",name:"Ghana",capital:"Accra"},
{flag:"🇹🇿",name:"Tanzania",capital:"Dodoma"},
{flag:"🇷🇼",name:"Rwanda",capital:"Kigali"},
{flag:"🇸🇳",name:"Senegal",capital:"Dakar"},
{flag:"🇹🇳",name:"Tunisia",capital:"Tunis"},
{flag:"🇺🇬",name:"Uganda",capital:"Kampala"},
{flag:"🇨🇮",name:"Ivory Coast",capital:"Yamoussoukro"},
{flag:"🇲🇬",name:"Madagascar",capital:"Antananarivo"},
{flag:"🇿🇼",name:"Zimbabwe",capital:"Harare"},
],
Asia:[
{flag:"🇯🇵",name:"Japan",capital:"Tokyo"},
{flag:"🇮🇳",name:"India",capital:"New Delhi"},
{flag:"🇨🇳",name:"China",capital:"Beijing"},
{flag:"🇰🇷",name:"South Korea",capital:"Seoul"},
{flag:"🇹🇭",name:"Thailand",capital:"Bangkok"},
{flag:"🇻🇳",name:"Vietnam",capital:"Hanoi"},
{flag:"🇹🇷",name:"Turkey",capital:"Ankara"},
{flag:"🇸🇬",name:"Singapore",capital:"Singapore"},
{flag:"🇵🇭",name:"Philippines",capital:"Manila"},
{flag:"🇮🇩",name:"Indonesia",capital:"Jakarta"},
{flag:"🇲🇾",name:"Malaysia",capital:"Kuala Lumpur"},
{flag:"🇮🇱",name:"Israel",capital:"Jerusalem"},
{flag:"🇳🇵",name:"Nepal",capital:"Kathmandu"},
{flag:"🇧🇩",name:"Bangladesh",capital:"Dhaka"},
{flag:"🇲🇳",name:"Mongolia",capital:"Ulaanbaatar"},
{flag:"🇱🇰",name:"Sri Lanka",capital:"Sri Jayawardenepura Kotte"},
{flag:"🇰🇭",name:"Cambodia",capital:"Phnom Penh"},
{flag:"🇦🇪",name:"United Arab Emirates",capital:"Abu Dhabi"},
{flag:"🇯🇴",name:"Jordan",capital:"Amman"},
{flag:"🇺🇿",name:"Uzbekistan",capital:"Tashkent"},
{flag:"🇲🇲",name:"Myanmar",capital:"Naypyidaw"},
{flag:"🇰🇿",name:"Kazakhstan",capital:"Astana"},
{flag:"🇱🇧",name:"Lebanon",capital:"Beirut"},
],
Europe:[
{flag:"🇫🇷",name:"France",capital:"Paris"},
{flag:"🇩🇪",name:"Germany",capital:"Berlin"},
{flag:"🇮🇹",name:"Italy",capital:"Rome"},
{flag:"🇪🇸",name:"Spain",capital:"Madrid"},
{flag:"🇬🇧",name:"United Kingdom",capital:"London"},
{flag:"🇳🇱",name:"Netherlands",capital:"Amsterdam"},
{flag:"🇸🇪",name:"Sweden",capital:"Stockholm"},
{flag:"🇬🇷",name:"Greece",capital:"Athens"},
{flag:"🇵🇹",name:"Portugal",capital:"Lisbon"},
{flag:"🇵🇱",name:"Poland",capital:"Warsaw"},
{flag:"🇳🇴",name:"Norway",capital:"Oslo"},
{flag:"🇨🇭",name:"Switzerland",capital:"Bern"},
{flag:"🇮🇪",name:"Ireland",capital:"Dublin"},
{flag:"🇦🇹",name:"Austria",capital:"Vienna"},
{flag:"🇭🇷",name:"Croatia",capital:"Zagreb"},
{flag:"🇫🇮",name:"Finland",capital:"Helsinki"},
{flag:"🇩🇰",name:"Denmark",capital:"Copenhagen"},
{flag:"🇨🇿",name:"Czech Republic",capital:"Prague"},
{flag:"🇭🇺",name:"Hungary",capital:"Budapest"},
{flag:"🇷🇴",name:"Romania",capital:"Bucharest"},
{flag:"🇧🇪",name:"Belgium",capital:"Brussels"},
{flag:"🇮🇸",name:"Iceland",capital:"Reykjavik"},
],
"North America":[
{flag:"🇺🇸",name:"United States",capital:"Washington D.C."},
{flag:"🇨🇦",name:"Canada",capital:"Ottawa"},
{flag:"🇲🇽",name:"Mexico",capital:"Mexico City"},
{flag:"🇨🇺",name:"Cuba",capital:"Havana"},
{flag:"🇯🇲",name:"Jamaica",capital:"Kingston"},
{flag:"🇨🇷",name:"Costa Rica",capital:"San José"},
{flag:"🇵🇦",name:"Panama",capital:"Panama City"},
{flag:"🇭🇹",name:"Haiti",capital:"Port-au-Prince"},
{flag:"🇩🇴",name:"Dominican Republic",capital:"Santo Domingo"},
{flag:"🇬🇹",name:"Guatemala",capital:"Guatemala City"},
{flag:"🇹🇹",name:"Trinidad and Tobago",capital:"Port of Spain"},
{flag:"🇧🇸",name:"Bahamas",capital:"Nassau"},
],
"South America":[
{flag:"🇧🇷",name:"Brazil",capital:"Brasília"},
{flag:"🇦🇷",name:"Argentina",capital:"Buenos Aires"},
{flag:"🇨🇴",name:"Colombia",capital:"Bogotá"},
{flag:"🇵🇪",name:"Peru",capital:"Lima"},
{flag:"🇨🇱",name:"Chile",capital:"Santiago"},
{flag:"🇪🇨",name:"Ecuador",capital:"Quito"},
{flag:"🇺🇾",name:"Uruguay",capital:"Montevideo"},
{flag:"🇻🇪",name:"Venezuela",capital:"Caracas"},
{flag:"🇧🇴",name:"Bolivia",capital:"Sucre"},
{flag:"🇵🇾",name:"Paraguay",capital:"Asunción"},
{flag:"🇬🇾",name:"Guyana",capital:"Georgetown"},
{flag:"🇸🇷",name:"Suriname",capital:"Paramaribo"},
],
Oceania:[
{flag:"🇦🇺",name:"Australia",capital:"Canberra"},
{flag:"🇳🇿",name:"New Zealand",capital:"Wellington"},
{flag:"🇫🇯",name:"Fiji",capital:"Suva"},
{flag:"🇵🇬",name:"Papua New Guinea",capital:"Port Moresby"},
{flag:"🇼🇸",name:"Samoa",capital:"Apia"},
{flag:"🇹🇴",name:"Tonga",capital:"Nukualofa"},
{flag:"🇻🇺",name:"Vanuatu",capital:"Port Vila"},
{flag:"🇸🇧",name:"Solomon Islands",capital:"Honiara"},
],
};
