const FOOD_DATA={
Africa:[
{img:"https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=400&h=300&fit=crop",dish:"Tagine",country:"Morocco",clues:["A slow-cooked stew named after the cone-shaped pot it's made in","Often combines meat with dried fruits like apricots and prunes","Seasoned with cumin, saffron, and cinnamon","Served with couscous or crusty bread","A staple of North African cuisine"]},
{img:"https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=400&h=300&fit=crop",dish:"Jollof Rice",country:"Nigeria",clues:["A one-pot rice dish cooked in a tomato and pepper sauce","Subject of a famous rivalry between West African nations","The rice absorbs a rich, smoky flavor called 'party jollof'","Seasoned with thyme, curry powder, and bay leaves","Often served at celebrations and parties"]},
{img:"https://images.unsplash.com/photo-1567364816519-cbc9c4ffe1eb?w=400&h=300&fit=crop",dish:"Bobotie",country:"South Africa",clues:["A baked dish with spiced minced meat and an egg custard topping","Influenced by Cape Malay cuisine","Contains dried fruit, chutney, and curry spices","Often served with yellow rice and banana slices","Considered the national dish of its country"]},
],
Asia:[
{img:"https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&h=300&fit=crop",dish:"Sushi",country:"Japan",clues:["Vinegared rice paired with raw fish or seafood","Originally a method of preserving fish in fermented rice","Comes in forms like nigiri, maki, and sashimi","Wasabi and soy sauce are traditional accompaniments","A UNESCO-recognized culinary tradition"]},
{img:"https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400&h=300&fit=crop",dish:"Pad Thai",country:"Thailand",clues:["Stir-fried rice noodles with tamarind sauce","Topped with crushed peanuts and a squeeze of lime","Often includes shrimp, tofu, or chicken with bean sprouts","Was promoted as a national dish in the 1930s","One of the most popular street foods in Southeast Asia"]},
{img:"https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop",dish:"Biryani",country:"India",clues:["A layered rice dish cooked with aromatic spices and meat","Uses basmati rice, saffron, and fried onions","Has regional variations like Hyderabadi and Lucknowi styles","Slow-cooked in a sealed pot called 'dum'","A Mughal-era dish that became a national favorite"]},
{img:"https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400&h=300&fit=crop",dish:"Dim Sum",country:"China",clues:["Small bite-sized portions served in steamer baskets","Traditionally enjoyed with tea in a practice called 'yum cha'","Includes dumplings, buns, and rice rolls","Originated in teahouses along the Silk Road","Carts are wheeled around for diners to choose from"]},
{img:"https://images.unsplash.com/photo-1583032015879-e5022cb87c3b?w=400&h=300&fit=crop",dish:"Bibimbap",country:"South Korea",clues:["A rice bowl topped with assorted vegetables, meat, and a fried egg","Mixed together with gochujang (red chili paste) before eating","The name literally means 'mixed rice'","Often served in a sizzling hot stone bowl called dolsot","A colorful dish representing balance and harmony"]},
{img:"https://images.unsplash.com/photo-1552611052-33e04de1b100?w=400&h=300&fit=crop",dish:"Pho",country:"Vietnam",clues:["A fragrant noodle soup with a slow-simmered bone broth","Served with fresh herbs, bean sprouts, and lime","Rice noodles are the base of this iconic street food","Star anise and cinnamon give the broth its distinctive flavor","Eaten for breakfast, lunch, and dinner"]},
{img:"https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400&h=300&fit=crop",dish:"Kebab",country:"Turkey",clues:["Grilled or roasted meat on skewers or a vertical rotisserie","Doner style is shaved from a rotating cone of meat","Served with flatbread, yogurt, and grilled vegetables","Has ancient origins dating back to medieval soldiers","Adana and Iskender are famous regional varieties"]},
{img:"https://images.unsplash.com/photo-1625220194771-7ebdea0b70b9?w=400&h=300&fit=crop",dish:"Rendang",country:"Indonesia",clues:["A dry curry of meat slow-cooked in coconut milk and spices","Voted the world's most delicious food by CNN","Originally from the Minangkabau people of West Sumatra","The sauce reduces until the meat is coated and caramelized","Traditionally served at ceremonial occasions"]},
],
Europe:[
{img:"https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=300&fit=crop",dish:"Pizza",country:"Italy",clues:["A flatbread topped with tomato sauce, cheese, and various toppings","The Margherita variety represents the national flag colors","Originated in Naples in the 18th century","Baked in a wood-fired oven at very high temperatures","UNESCO recognized its art of making as cultural heritage"]},
{img:"https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=300&fit=crop",dish:"Coq au Vin",country:"France",clues:["Chicken braised in wine with mushrooms and onions","A classic of rustic countryside cooking","Julia Child helped popularize it internationally","The sauce is thickened with the bird's own blood traditionally","Burgundy wine is the traditional choice for the braise"]},
{img:"https://images.unsplash.com/photo-1600335895229-6e75511892c8?w=400&h=300&fit=crop",dish:"Paella",country:"Spain",clues:["A rice dish cooked in a wide, shallow pan over an open fire","Saffron gives it a distinctive golden color","The original version uses rabbit, snails, and green beans","Named after the pan it's cooked in, from Latin 'patella'","Originated in the Valencia region"]},
{img:"https://images.unsplash.com/photo-1585325701956-60dd9c8553bc?w=400&h=300&fit=crop",dish:"Fish and Chips",country:"United Kingdom",clues:["Battered and deep-fried fish served with thick-cut fries","Traditionally wrapped in newspaper","Mushy peas and malt vinegar are classic accompaniments","Became a working-class staple in the 19th century","Cod and haddock are the most popular fish choices"]},
{img:"https://images.unsplash.com/photo-1599921841143-819065a55cc6?w=400&h=300&fit=crop",dish:"Moussaka",country:"Greece",clues:["A layered casserole with eggplant, meat sauce, and béchamel","Similar to lasagna but uses sliced vegetables instead of pasta","Seasoned with cinnamon and allspice","Baked until the top is golden and bubbly","A comfort food staple of Mediterranean cuisine"]},
{img:"https://images.unsplash.com/photo-1520201163981-8cc95007dd2a?w=400&h=300&fit=crop",dish:"Bratwurst",country:"Germany",clues:["A grilled sausage made from pork, beef, or veal","Served in a bread roll with mustard","Nuremberg and Thuringia have famous regional varieties","A staple at beer gardens and Christmas markets","The name comes from Old High German for 'finely chopped meat'"]},
{img:"https://images.unsplash.com/photo-1588625500633-a0832c468fab?w=400&h=300&fit=crop",dish:"Pierogi",country:"Poland",clues:["Filled dumplings that are boiled then often pan-fried","Common fillings include potato and cheese, sauerkraut, or meat","Served with sour cream and fried onions","A comfort food eaten year-round but especially at holidays","The name comes from a Slavic word meaning 'feast'"]},
],
"North America":[
{img:"https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=400&h=300&fit=crop",dish:"Tacos",country:"Mexico",clues:["Corn or flour tortillas filled with meat, salsa, and toppings","Al pastor style features spit-roasted pork with pineapple","Street vendors called taqueros are found on every corner","Cilantro and onion are the classic simple toppings","An ancient food dating back to pre-Columbian times"]},
{img:"https://images.unsplash.com/photo-1550547660-d9450f859349?w=400&h=300&fit=crop",dish:"Hamburger",country:"United States",clues:["A ground beef patty served in a sliced bun","Became an American icon at the 1904 World's Fair","Cheese, lettuce, tomato, and pickles are classic toppings","Fast food chains made it the world's most popular sandwich","White Castle was the first chain dedicated to this food"]},
{img:"https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop",dish:"Poutine",country:"Canada",clues:["French fries topped with cheese curds and brown gravy","The cheese must squeak when fresh","Originated in rural Quebec in the 1950s","Now found in gourmet versions with foie gras or lobster","A beloved late-night comfort food"]},
{img:"https://images.unsplash.com/photo-1534352956036-cd81e27dd615?w=400&h=300&fit=crop",dish:"Jerk Chicken",country:"Jamaica",clues:["Chicken marinated in a fiery spice blend and grilled over pimento wood","Scotch bonnet peppers and allspice are the key ingredients","Originated with the Maroon people in the Blue Mountains","The word 'jerk' refers to the method of poking holes in the meat","Often served with rice and peas and festival bread"]},
],
"South America":[
{img:"https://images.unsplash.com/photo-1558030006-450675393462?w=400&h=300&fit=crop",dish:"Asado",country:"Argentina",clues:["A barbecue tradition featuring various cuts of beef grilled over wood","Chimichurri sauce is the essential accompaniment","A social event that can last for hours","The grill master is called an 'asador'","Beef ribs, chorizo, and blood sausage are typical"]},
{img:"https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&h=300&fit=crop",dish:"Ceviche",country:"Peru",clues:["Raw fish cured in citrus juice, typically lime","The acid 'cooks' the fish without heat","Served with red onion, chili peppers, and sweet potato","Considered the national dish and a point of cultural pride","Best eaten fresh, within minutes of preparation"]},
{img:"https://images.unsplash.com/photo-1536304993881-460e32f50f47?w=400&h=300&fit=crop",dish:"Feijoada",country:"Brazil",clues:["A hearty black bean stew with pork and beef","Traditionally served on Wednesdays and Saturdays","Accompanied by rice, collard greens, and orange slices","Has roots in the food of enslaved Africans","Considered the national dish, enjoyed across all social classes"]},
{img:"https://images.unsplash.com/photo-1599139849623-91690e89e tried?w=400&h=300&fit=crop",dish:"Empanadas",country:"Colombia",clues:["Stuffed pastries that are baked or fried","Fillings range from beef and chicken to cheese and fruit","Found throughout Latin America with regional variations","The name comes from the Spanish word 'empanar' meaning to wrap","A popular street food and party snack"]},
],
Oceania:[
{img:"https://images.unsplash.com/photo-1607478900766-efe13248b125?w=400&h=300&fit=crop",dish:"Meat Pie",country:"Australia",clues:["A handheld pie filled with minced meat and gravy","Sold at bakeries, gas stations, and sporting events","Tomato sauce (ketchup) is the essential topping","The national food, with over 270 million eaten per year","Often enjoyed at cricket and football matches"]},
{img:"https://images.unsplash.com/photo-1626200419199-391ae4be7a41?w=400&h=300&fit=crop",dish:"Hangi",country:"New Zealand",clues:["A traditional Māori method of cooking food underground","Meat and vegetables are placed on heated rocks in a pit","Covered with earth and slow-cooked for several hours","The food absorbs a unique smoky, earthy flavor","A centerpiece of cultural gatherings and celebrations"]},
]
};
